artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_source: Data/wafer_dataset.csv
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  data_to_store: artifacts/data_ingestion/raw_data.csv 



